# Generated by Django 4.1.7 on 2023-03-05 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceProductsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('sale_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('basic_points', models.SmallIntegerField()),
                ('category', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=64)),
                ('points', models.SmallIntegerField(default=0)),
                ('invoices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loyalty_program_app.invoices')),
            ],
        ),
        migrations.AddField(
            model_name='invoices',
            name='products',
            field=models.ManyToManyField(through='Loyalty_program_app.InvoiceProductsList', to='Loyalty_program_app.products'),
        ),
        migrations.AddField(
            model_name='invoiceproductslist',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loyalty_program_app.invoices'),
        ),
        migrations.AddField(
            model_name='invoiceproductslist',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loyalty_program_app.products'),
        ),
    ]
