# Generated by Django 4.1.7 on 2023-03-05 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Loyalty_program_app', '0003_alter_invoices_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproductslist',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Loyalty_program_app.invoices'),
        ),
        migrations.AlterField(
            model_name='invoiceproductslist',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Loyalty_program_app.products'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='invoices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Loyalty_program_app.invoices'),
        ),
    ]
