# Generated by Django 4.1.7 on 2023-03-08 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Loyalty_program_app', '0004_alter_invoiceproductslist_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='invoices',
        ),
        migrations.AddField(
            model_name='invoices',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Loyalty_program_app.userprofile'),
        ),
    ]
