# Generated by Django 4.1.7 on 2023-03-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loyalty_program_app', '0006_alter_products_basic_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproductslist',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
