# Generated by Django 4.1.7 on 2023-03-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loyalty_program_app', '0008_alter_userprofile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='countpoints',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoices',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
