# Generated by Django 4.1.7 on 2023-03-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loyalty_program_app', '0010_prizes_prizeopinions_carts_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='prize',
            field=models.ManyToManyField(through='Loyalty_program_app.CartItems', to='Loyalty_program_app.prizes'),
        ),
    ]
