# Generated by Django 4.1.7 on 2023-03-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loyalty_program_app', '0011_carts_prize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='prize',
            new_name='item',
        ),
    ]
