# Generated by Django 4.1.7 on 2023-03-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loyalty_program_app', '0012_rename_prize_carts_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='item',
            new_name='prize',
        ),
    ]
