# Generated by Django 4.1.7 on 2023-03-18 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Loyalty_program_app', '0013_rename_item_carts_prize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='user',
        ),
        migrations.AddField(
            model_name='invoices',
            name='purchaser_nip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Loyalty_program_app.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_nip',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
