# Generated by Django 4.1.7 on 2023-03-18 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loyalty_program_app', '0014_invoices_purchaser_nip_userprofile_nip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='purchaser_nip',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nip',
        ),
    ]
