# Generated by Django 4.1.7 on 2023-03-18 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Loyalty_program_app', '0014_remove_invoices_user_invoices_purchaser_nip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_nip',
        ),
        migrations.AddField(
            model_name='invoices',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Loyalty_program_app.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nip',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='purchaser_nip',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
