# Generated by Django 4.1.7 on 2023-03-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loyalty_program_app', '0015_remove_invoices_purchaser_nip_remove_userprofile_nip'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='purchaser_nip',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nip',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
